  steps:
  
    # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west9-docker.pkg.dev/turnkey-world-334318/cloud-run-source-deploy/guehelloworld2:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west9-docker.pkg.dev/turnkey-world-334318/cloud-run-source-deploy/guehelloworld2:$COMMIT_SHA']
  
    # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'guehelloworld2'
    - '--image'
    - 'europe-west9-docker.pkg.dev/turnkey-world-334318/cloud-run-source-deploy/guehelloworld2:$COMMIT_SHA'
    - '--region'
    - 'europe-west9'
    - 'allow-unauthenticated'
  images:
    - 'europe-west9-docker.pkg.dev/turnkey-world-334318/cloud-run-source-deploy/guehelloworld2:$COMMIT_SHA'

